package top.e404.eorm.dialect

import top.e404.eorm.generator.IdStrategy
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.util.Date

class PostgreSqlDialect : BaseDialect() {
    override fun wrapName(name: String): String = "\"$name\""
    override fun getSqlType(type: Class<*>, length: Int): String {
        return when (type) {
            Boolean::class.java, java.lang.Boolean::class.java -> "BOOLEAN"
            String::class.java -> "VARCHAR($length)"
            Int::class.java, Integer::class.java -> "INTEGER"
            Long::class.java, java.lang.Long::class.java -> "BIGINT"
            Double::class.java, java.lang.Double::class.java -> "DOUBLE PRECISION"
            Date::class.java, java.util.Date::class.java -> "TIMESTAMP"
            LocalDateTime::class.java -> "TIMESTAMP"
            LocalDate::class.java -> "DATE"
            LocalTime::class.java -> "TIME"
            else -> "VARCHAR(255)"
        }
    }

    override fun getPrimaryKeyDefinition(strategy: IdStrategy): String =
        if (strategy == IdStrategy.AUTO) "PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" else "PRIMARY KEY"

    override fun buildPaginationSql(sql: String, offset: Long, limit: Long): String {
        return "$sql LIMIT $limit OFFSET $offset"
    }
}
