package top.e404.eorm.dialect

import top.e404.eorm.generator.IdStrategy
import java.text.SimpleDateFormat
import java.util.Date
import java.time.LocalDateTime
import java.time.LocalDate
import java.time.LocalTime
import java.time.format.DateTimeFormatter

interface SqlDialect {
    fun wrapName(name: String): String
    fun getSqlType(type: Class<*>, length: Int): String
    fun getPrimaryKeyDefinition(strategy: IdStrategy): String
    fun valueToSql(value: Any?): String
}

abstract class BaseDialect : SqlDialect {
    override fun valueToSql(value: Any?): String {
        return when (value) {
            null -> "NULL"
            is Number, is Boolean -> value.toString()
            is String -> "'${value.replace("'", "''")}'"
            is Date -> "'${SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(value)}'"
            is LocalDateTime -> "'${DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(value)}'"
            is LocalDate -> "'${DateTimeFormatter.ofPattern("yyyy-MM-dd").format(value)}'"
            is LocalTime -> "'${DateTimeFormatter.ofPattern("HH:mm:ss").format(value)}'"
            else -> "'${value.toString().replace("'", "''")}'"
        }
    }
}

class MySqlDialect : BaseDialect() {
    override fun wrapName(name: String): String = "`$name`"
    override fun getSqlType(type: Class<*>, length: Int): String {
        return when (type) {
            Boolean::class.java, java.lang.Boolean::class.java -> "TINYINT"
            String::class.java -> "VARCHAR($length)"
            Int::class.java, Integer::class.java -> "INT"
            Long::class.java, java.lang.Long::class.java -> "BIGINT"
            Double::class.java, java.lang.Double::class.java -> "DOUBLE"
            Date::class.java, java.util.Date::class.java -> "DATETIME"
            LocalDateTime::class.java -> "DATETIME"
            LocalDate::class.java -> "DATE"
            LocalTime::class.java -> "TIME"
            else -> "VARCHAR(255)"
        }
    }
    override fun getPrimaryKeyDefinition(strategy: IdStrategy): String = if (strategy == IdStrategy.AUTO) "PRIMARY KEY AUTO_INCREMENT" else "PRIMARY KEY"
}

class H2Dialect : BaseDialect() {
    override fun wrapName(name: String): String = name
    override fun getSqlType(type: Class<*>, length: Int): String {
        return when (type) {
            Boolean::class.java, java.lang.Boolean::class.java -> "BOOLEAN"
            String::class.java -> "VARCHAR($length)"
            Int::class.java, Integer::class.java -> "INT"
            Long::class.java, java.lang.Long::class.java -> "BIGINT"
            Double::class.java, java.lang.Double::class.java -> "DOUBLE"
            Date::class.java, java.util.Date::class.java -> "DATETIME"
            LocalDateTime::class.java -> "DATETIME"
            LocalDate::class.java -> "DATE"
            LocalTime::class.java -> "TIME"
            else -> "VARCHAR(255)"
        }
    }
    override fun getPrimaryKeyDefinition(strategy: IdStrategy): String = if (strategy == IdStrategy.AUTO) "PRIMARY KEY AUTO_INCREMENT" else "PRIMARY KEY"
}

class PostgreSqlDialect : BaseDialect() {
    override fun wrapName(name: String): String = "\"$name\""
    override fun getSqlType(type: Class<*>, length: Int): String {
        return when (type) {
            Boolean::class.java, java.lang.Boolean::class.java -> "BOOLEAN"
            String::class.java -> "VARCHAR($length)"
            Int::class.java, Integer::class.java -> "INTEGER"
            Long::class.java, java.lang.Long::class.java -> "BIGINT"
            Double::class.java, java.lang.Double::class.java -> "DOUBLE PRECISION"
            Date::class.java, java.util.Date::class.java -> "TIMESTAMP"
            LocalDateTime::class.java -> "TIMESTAMP"
            LocalDate::class.java -> "DATE"
            LocalTime::class.java -> "TIME"
            else -> "VARCHAR(255)"
        }
    }

    override fun getPrimaryKeyDefinition(strategy: IdStrategy): String =
        if (strategy == IdStrategy.AUTO) "PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" else "PRIMARY KEY"
}

class SqliteDialect : BaseDialect() {
    override fun wrapName(name: String): String = "\"$name\""
    override fun getSqlType(type: Class<*>, length: Int): String {
        return when (type) {
            Boolean::class.java, java.lang.Boolean::class.java -> "INTEGER"
            String::class.java -> "TEXT"
            Int::class.java, Integer::class.java -> "INTEGER"
            Long::class.java, java.lang.Long::class.java -> "INTEGER"
            Double::class.java, java.lang.Double::class.java -> "REAL"
            Date::class.java, java.util.Date::class.java -> "TEXT"
            LocalDateTime::class.java -> "TEXT"
            LocalDate::class.java -> "TEXT"
            LocalTime::class.java -> "TEXT"
            else -> "TEXT"
        }
    }

    override fun getPrimaryKeyDefinition(strategy: IdStrategy): String =
        if (strategy == IdStrategy.AUTO) "PRIMARY KEY AUTOINCREMENT" else "PRIMARY KEY"
}

enum class DbType(val dialect: SqlDialect) {
    MYSQL(MySqlDialect()),
    H2(H2Dialect()),
    POSTGRESQL(PostgreSqlDialect()),
    SQLITE(SqliteDialect())
}
